var annotated_dup =
[
    [ "shkyera", "namespaceshkyera.html", [
      [ "Asset", "classshkyera_1_1_asset.html", "classshkyera_1_1_asset" ],
      [ "AssetManager", "classshkyera_1_1_asset_manager.html", "classshkyera_1_1_asset_manager" ],
      [ "File", "classshkyera_1_1_file.html", "classshkyera_1_1_file" ],
      [ "Directory", "classshkyera_1_1_directory.html", "classshkyera_1_1_directory" ],
      [ "Image", "classshkyera_1_1_image.html", "classshkyera_1_1_image" ],
      [ "Material", "classshkyera_1_1_material.html", "classshkyera_1_1_material" ],
      [ "Mesh", "classshkyera_1_1_mesh.html", "classshkyera_1_1_mesh" ],
      [ "Shader", "classshkyera_1_1_shader.html", "classshkyera_1_1_shader" ],
      [ "Wireframe", "classshkyera_1_1_wireframe.html", "classshkyera_1_1_wireframe" ],
      [ "AmbientLightComponent", "classshkyera_1_1_ambient_light_component.html", "classshkyera_1_1_ambient_light_component" ],
      [ "BaseComponent", "classshkyera_1_1_base_component.html", "classshkyera_1_1_base_component" ],
      [ "BoxColliderComponent", "classshkyera_1_1_box_collider_component.html", "classshkyera_1_1_box_collider_component" ],
      [ "CameraComponent", "classshkyera_1_1_camera_component.html", "classshkyera_1_1_camera_component" ],
      [ "DirectionalLightComponent", "classshkyera_1_1_directional_light_component.html", "classshkyera_1_1_directional_light_component" ],
      [ "ModelComponent", "classshkyera_1_1_model_component.html", "classshkyera_1_1_model_component" ],
      [ "NameComponent", "classshkyera_1_1_name_component.html", "classshkyera_1_1_name_component" ],
      [ "PointLightComponent", "classshkyera_1_1_point_light_component.html", "classshkyera_1_1_point_light_component" ],
      [ "SkyboxComponent", "classshkyera_1_1_skybox_component.html", "classshkyera_1_1_skybox_component" ],
      [ "TransformComponent", "classshkyera_1_1_transform_component.html", "classshkyera_1_1_transform_component" ],
      [ "WireframeComponent", "classshkyera_1_1_wireframe_component.html", "classshkyera_1_1_wireframe_component" ],
      [ "EntityProvider", "classshkyera_1_1_entity_provider.html", "classshkyera_1_1_entity_provider" ],
      [ "Registry", "classshkyera_1_1_registry.html", "classshkyera_1_1_registry" ],
      [ "SparseSetBase", "classshkyera_1_1_sparse_set_base.html", "classshkyera_1_1_sparse_set_base" ],
      [ "SparseSet", "classshkyera_1_1_sparse_set.html", "classshkyera_1_1_sparse_set" ],
      [ "InputManager", "classshkyera_1_1_input_manager.html", "classshkyera_1_1_input_manager" ],
      [ "Box", "structshkyera_1_1_box.html", "structshkyera_1_1_box" ],
      [ "Ray", "structshkyera_1_1_ray.html", "structshkyera_1_1_ray" ],
      [ "CubeMap", "classshkyera_1_1_cube_map.html", "classshkyera_1_1_cube_map" ],
      [ "FrameBuffer", "classshkyera_1_1_frame_buffer.html", "classshkyera_1_1_frame_buffer" ],
      [ "ShaderProgram", "classshkyera_1_1_shader_program.html", "classshkyera_1_1_shader_program" ],
      [ "Texture", "classshkyera_1_1_texture.html", "classshkyera_1_1_texture" ],
      [ "Runtime", "classshkyera_1_1_runtime.html", "classshkyera_1_1_runtime" ],
      [ "CameraMovementSystem", "classshkyera_1_1_camera_movement_system.html", "classshkyera_1_1_camera_movement_system" ],
      [ "DevelopmentRendererSystem", "classshkyera_1_1_development_renderer_system.html", "classshkyera_1_1_development_renderer_system" ],
      [ "ObjectSelectionSystem", "classshkyera_1_1_object_selection_system.html", "classshkyera_1_1_object_selection_system" ],
      [ "RenderingSystem", "classshkyera_1_1_rendering_system.html", "classshkyera_1_1_rendering_system" ],
      [ "ColorSelector", "classshkyera_1_1_color_selector.html", "classshkyera_1_1_color_selector" ],
      [ "FileSelector", "classshkyera_1_1_file_selector.html", "classshkyera_1_1_file_selector" ],
      [ "FloatSlider", "classshkyera_1_1_float_slider.html", "classshkyera_1_1_float_slider" ],
      [ "AmbientLightComponentUI", "classshkyera_1_1_ambient_light_component_u_i.html", "classshkyera_1_1_ambient_light_component_u_i" ],
      [ "DirectionalLightComponentUI", "classshkyera_1_1_directional_light_component_u_i.html", "classshkyera_1_1_directional_light_component_u_i" ],
      [ "ModelComponentUI", "classshkyera_1_1_model_component_u_i.html", "classshkyera_1_1_model_component_u_i" ],
      [ "PointLightComponentUI", "classshkyera_1_1_point_light_component_u_i.html", "classshkyera_1_1_point_light_component_u_i" ],
      [ "TransformComponentUI", "classshkyera_1_1_transform_component_u_i.html", "classshkyera_1_1_transform_component_u_i" ],
      [ "WireframeComponentUI", "classshkyera_1_1_wireframe_component_u_i.html", "classshkyera_1_1_wireframe_component_u_i" ],
      [ "ComponentUI", "classshkyera_1_1_component_u_i.html", "classshkyera_1_1_component_u_i" ],
      [ "UI", "classshkyera_1_1_u_i.html", "classshkyera_1_1_u_i" ],
      [ "Widget", "classshkyera_1_1_widget.html", "classshkyera_1_1_widget" ],
      [ "Log", "classshkyera_1_1_log.html", "classshkyera_1_1_log" ],
      [ "LogVerbose", "classshkyera_1_1_log_verbose.html", "classshkyera_1_1_log_verbose" ],
      [ "LogInfo", "classshkyera_1_1_log_info.html", "classshkyera_1_1_log_info" ],
      [ "LogSuccess", "classshkyera_1_1_log_success.html", "classshkyera_1_1_log_success" ],
      [ "LogError", "classshkyera_1_1_log_error.html", "classshkyera_1_1_log_error" ],
      [ "ConsoleWidget", "classshkyera_1_1_console_widget.html", "classshkyera_1_1_console_widget" ],
      [ "FilesystemWidget", "classshkyera_1_1_filesystem_widget.html", "classshkyera_1_1_filesystem_widget" ],
      [ "ObjectsWidget", "classshkyera_1_1_objects_widget.html", "classshkyera_1_1_objects_widget" ],
      [ "PreviewWidget", "classshkyera_1_1_preview_widget.html", "classshkyera_1_1_preview_widget" ],
      [ "PropertiesWidget", "classshkyera_1_1_properties_widget.html", "classshkyera_1_1_properties_widget" ],
      [ "CameraPropertiesWidget", "classshkyera_1_1_camera_properties_widget.html", "classshkyera_1_1_camera_properties_widget" ],
      [ "EnvironmentPropertiesWidget", "classshkyera_1_1_environment_properties_widget.html", "classshkyera_1_1_environment_properties_widget" ],
      [ "SceneWidget", "classshkyera_1_1_scene_widget.html", "classshkyera_1_1_scene_widget" ]
    ] ],
    [ "std", "namespacestd.html", [
      [ "std", null, [
        [ "hash< glm::vec3 >", "structstd_1_1std_1_1hash_3_01glm_1_1vec3_01_4.html", "structstd_1_1std_1_1hash_3_01glm_1_1vec3_01_4" ]
      ] ]
    ] ]
];