var annotated_dup =
[
    [ "shkyera", "namespaceshkyera.html", [
      [ "common", "namespaceshkyera_1_1common.html", [
        [ "BiMap", "classshkyera_1_1common_1_1_bi_map.html", "classshkyera_1_1common_1_1_bi_map" ]
      ] ],
      [ "random", "namespaceshkyera_1_1random.html", [
        [ "Normal", "classshkyera_1_1random_1_1_normal.html", "classshkyera_1_1random_1_1_normal" ],
        [ "Sphere", "classshkyera_1_1random_1_1_sphere.html", "classshkyera_1_1random_1_1_sphere" ],
        [ "Uniform", "classshkyera_1_1random_1_1_uniform.html", "classshkyera_1_1random_1_1_uniform" ]
      ] ],
      [ "utils", "namespaceshkyera_1_1utils.html", [
        [ "assets", "namespaceshkyera_1_1utils_1_1assets.html", [
          [ "CubeMapLoader", "classshkyera_1_1utils_1_1assets_1_1_cube_map_loader.html", "classshkyera_1_1utils_1_1assets_1_1_cube_map_loader" ],
          [ "FactoryAssetLoader", "classshkyera_1_1utils_1_1assets_1_1_factory_asset_loader.html", "classshkyera_1_1utils_1_1assets_1_1_factory_asset_loader" ],
          [ "MaterialLoader", "classshkyera_1_1utils_1_1assets_1_1_material_loader.html", "classshkyera_1_1utils_1_1assets_1_1_material_loader" ],
          [ "PathAssetLoader", "classshkyera_1_1utils_1_1assets_1_1_path_asset_loader.html", "classshkyera_1_1utils_1_1assets_1_1_path_asset_loader" ],
          [ "ShaderLoader", "classshkyera_1_1utils_1_1assets_1_1_shader_loader.html", "classshkyera_1_1utils_1_1assets_1_1_shader_loader" ]
        ] ]
      ] ],
      [ "AABB", "structshkyera_1_1_a_a_b_b.html", "structshkyera_1_1_a_a_b_b" ],
      [ "AmbientLightComponent", "structshkyera_1_1_ambient_light_component.html", "structshkyera_1_1_ambient_light_component" ],
      [ "AmbientLightComponentUI", "classshkyera_1_1_ambient_light_component_u_i.html", "classshkyera_1_1_ambient_light_component_u_i" ],
      [ "AssetComponent", "structshkyera_1_1_asset_component.html", "structshkyera_1_1_asset_component" ],
      [ "AssetLoader", "classshkyera_1_1_asset_loader.html", "classshkyera_1_1_asset_loader" ],
      [ "AssetRoot", "structshkyera_1_1_asset_root.html", "structshkyera_1_1_asset_root" ],
      [ "AssetSelector", "classshkyera_1_1_asset_selector.html", "classshkyera_1_1_asset_selector" ],
      [ "Audio", "classshkyera_1_1_audio.html", "classshkyera_1_1_audio" ],
      [ "AudioSourceComponent", "classshkyera_1_1_audio_source_component.html", "classshkyera_1_1_audio_source_component" ],
      [ "AudioSourceComponentUI", "classshkyera_1_1_audio_source_component_u_i.html", "classshkyera_1_1_audio_source_component_u_i" ],
      [ "AudioSystem", "classshkyera_1_1_audio_system.html", "classshkyera_1_1_audio_system" ],
      [ "BaseComponent", "classshkyera_1_1_base_component.html", "classshkyera_1_1_base_component" ],
      [ "BillboardComponent", "structshkyera_1_1_billboard_component.html", "structshkyera_1_1_billboard_component" ],
      [ "BillboardComponentUI", "classshkyera_1_1_billboard_component_u_i.html", "classshkyera_1_1_billboard_component_u_i" ],
      [ "BooleanSelector", "classshkyera_1_1_boolean_selector.html", "classshkyera_1_1_boolean_selector" ],
      [ "BoxColliderComponent", "structshkyera_1_1_box_collider_component.html", "structshkyera_1_1_box_collider_component" ],
      [ "CameraComponent", "classshkyera_1_1_camera_component.html", "classshkyera_1_1_camera_component" ],
      [ "CameraComponentUI", "classshkyera_1_1_camera_component_u_i.html", "classshkyera_1_1_camera_component_u_i" ],
      [ "CameraMovementSystem", "classshkyera_1_1_camera_movement_system.html", "classshkyera_1_1_camera_movement_system" ],
      [ "CameraPropertiesWidget", "classshkyera_1_1_camera_properties_widget.html", "classshkyera_1_1_camera_properties_widget" ],
      [ "Clock", "structshkyera_1_1_clock.html", "structshkyera_1_1_clock" ],
      [ "ColorSelector", "classshkyera_1_1_color_selector.html", "classshkyera_1_1_color_selector" ],
      [ "ComponentUI", "classshkyera_1_1_component_u_i.html", "classshkyera_1_1_component_u_i" ],
      [ "ConsoleWidget", "classshkyera_1_1_console_widget.html", "classshkyera_1_1_console_widget" ],
      [ "CubeMap", "classshkyera_1_1_cube_map.html", "classshkyera_1_1_cube_map" ],
      [ "DepthAtlasFrameBuffer", "classshkyera_1_1_depth_atlas_frame_buffer.html", "classshkyera_1_1_depth_atlas_frame_buffer" ],
      [ "DepthCubeMapFrameBuffer", "classshkyera_1_1_depth_cube_map_frame_buffer.html", "classshkyera_1_1_depth_cube_map_frame_buffer" ],
      [ "DirectionalLightComponent", "structshkyera_1_1_directional_light_component.html", "structshkyera_1_1_directional_light_component" ],
      [ "DirectionalLightComponentUI", "classshkyera_1_1_directional_light_component_u_i.html", "classshkyera_1_1_directional_light_component_u_i" ],
      [ "DirectoryComponent", "structshkyera_1_1_directory_component.html", "structshkyera_1_1_directory_component" ],
      [ "EntityHierarchy", "classshkyera_1_1_entity_hierarchy.html", "classshkyera_1_1_entity_hierarchy" ],
      [ "EntityProvider", "classshkyera_1_1_entity_provider.html", "classshkyera_1_1_entity_provider" ],
      [ "EnumSelector", "classshkyera_1_1_enum_selector.html", "classshkyera_1_1_enum_selector" ],
      [ "Environment", "structshkyera_1_1_environment.html", null ],
      [ "EnvironmentPropertiesWidget", "classshkyera_1_1_environment_properties_widget.html", "classshkyera_1_1_environment_properties_widget" ],
      [ "FilesystemWidget", "classshkyera_1_1_filesystem_widget.html", "classshkyera_1_1_filesystem_widget" ],
      [ "FloatSlider", "classshkyera_1_1_float_slider.html", "classshkyera_1_1_float_slider" ],
      [ "GizmoHandleComponent", "classshkyera_1_1_gizmo_handle_component.html", "classshkyera_1_1_gizmo_handle_component" ],
      [ "GizmoSystem", "classshkyera_1_1_gizmo_system.html", "classshkyera_1_1_gizmo_system" ],
      [ "GlobalPathEqual", "structshkyera_1_1_global_path_equal.html", "structshkyera_1_1_global_path_equal" ],
      [ "GlobalPathHash", "structshkyera_1_1_global_path_hash.html", "structshkyera_1_1_global_path_hash" ],
      [ "Image", "classshkyera_1_1_image.html", "classshkyera_1_1_image" ],
      [ "InputManager", "classshkyera_1_1_input_manager.html", "classshkyera_1_1_input_manager" ],
      [ "InspectorWidget", "classshkyera_1_1_inspector_widget.html", "classshkyera_1_1_inspector_widget" ],
      [ "InstanceCounter", "structshkyera_1_1_instance_counter.html", "structshkyera_1_1_instance_counter" ],
      [ "JobSystem", "classshkyera_1_1_job_system.html", "classshkyera_1_1_job_system" ],
      [ "Log", "classshkyera_1_1_log.html", "classshkyera_1_1_log" ],
      [ "LogError", "classshkyera_1_1_log_error.html", "classshkyera_1_1_log_error" ],
      [ "LogInfo", "classshkyera_1_1_log_info.html", "classshkyera_1_1_log_info" ],
      [ "LogSuccess", "classshkyera_1_1_log_success.html", "classshkyera_1_1_log_success" ],
      [ "LogVerbose", "classshkyera_1_1_log_verbose.html", "classshkyera_1_1_log_verbose" ],
      [ "Material", "structshkyera_1_1_material.html", "structshkyera_1_1_material" ],
      [ "Mesh", "classshkyera_1_1_mesh.html", "classshkyera_1_1_mesh" ],
      [ "ModelComponent", "classshkyera_1_1_model_component.html", "classshkyera_1_1_model_component" ],
      [ "ModelComponentUI", "classshkyera_1_1_model_component_u_i.html", "classshkyera_1_1_model_component_u_i" ],
      [ "NameComponent", "classshkyera_1_1_name_component.html", "classshkyera_1_1_name_component" ],
      [ "ObjectSelectionSystem", "classshkyera_1_1_object_selection_system.html", "classshkyera_1_1_object_selection_system" ],
      [ "ObjectsWidget", "classshkyera_1_1_objects_widget.html", "classshkyera_1_1_objects_widget" ],
      [ "OpenGLResourceTag", "structshkyera_1_1_open_g_l_resource_tag.html", null ],
      [ "OverlayModelComponent", "classshkyera_1_1_overlay_model_component.html", "classshkyera_1_1_overlay_model_component" ],
      [ "ParticleEmitterComponent", "structshkyera_1_1_particle_emitter_component.html", "structshkyera_1_1_particle_emitter_component" ],
      [ "ParticleEmitterComponentUI", "classshkyera_1_1_particle_emitter_component_u_i.html", "classshkyera_1_1_particle_emitter_component_u_i" ],
      [ "ParticleSystem", "classshkyera_1_1_particle_system.html", "classshkyera_1_1_particle_system" ],
      [ "PointLightComponent", "structshkyera_1_1_point_light_component.html", "structshkyera_1_1_point_light_component" ],
      [ "PointLightComponentUI", "classshkyera_1_1_point_light_component_u_i.html", "classshkyera_1_1_point_light_component_u_i" ],
      [ "Policy", "structshkyera_1_1_policy.html", "structshkyera_1_1_policy" ],
      [ "PostProcessingVolumeComponent", "structshkyera_1_1_post_processing_volume_component.html", "structshkyera_1_1_post_processing_volume_component" ],
      [ "PostProcessingVolumeComponentUI", "classshkyera_1_1_post_processing_volume_component_u_i.html", "classshkyera_1_1_post_processing_volume_component_u_i" ],
      [ "ProfileBlock", "structshkyera_1_1_profile_block.html", "structshkyera_1_1_profile_block" ],
      [ "ProfileGuard", "classshkyera_1_1_profile_guard.html", "classshkyera_1_1_profile_guard" ],
      [ "Profiler", "classshkyera_1_1_profiler.html", "classshkyera_1_1_profiler" ],
      [ "ProfilerWidget", "classshkyera_1_1_profiler_widget.html", "classshkyera_1_1_profiler_widget" ],
      [ "PropertiesWidget", "classshkyera_1_1_properties_widget.html", "classshkyera_1_1_properties_widget" ],
      [ "Ray", "structshkyera_1_1_ray.html", "structshkyera_1_1_ray" ],
      [ "ReadAccess", "structshkyera_1_1_read_access.html", "structshkyera_1_1_read_access" ],
      [ "Registry", "classshkyera_1_1_registry.html", "classshkyera_1_1_registry" ],
      [ "RegistryViewer", "classshkyera_1_1_registry_viewer.html", "classshkyera_1_1_registry_viewer" ],
      [ "RenderingSystem", "classshkyera_1_1_rendering_system.html", "classshkyera_1_1_rendering_system" ],
      [ "RenderingTextureComponent", "structshkyera_1_1_rendering_texture_component.html", "structshkyera_1_1_rendering_texture_component" ],
      [ "ResourceTag", "structshkyera_1_1_resource_tag.html", null ],
      [ "RuntimeCamera", "structshkyera_1_1_runtime_camera.html", null ],
      [ "RuntimeWidget", "classshkyera_1_1_runtime_widget.html", "classshkyera_1_1_runtime_widget" ],
      [ "SceneCamera", "structshkyera_1_1_scene_camera.html", null ],
      [ "SceneFrameBuffer", "classshkyera_1_1_scene_frame_buffer.html", "classshkyera_1_1_scene_frame_buffer" ],
      [ "SceneWidget", "classshkyera_1_1_scene_widget.html", "classshkyera_1_1_scene_widget" ],
      [ "SelectedAssetComponent", "structshkyera_1_1_selected_asset_component.html", null ],
      [ "SelectedEntityComponent", "structshkyera_1_1_selected_entity_component.html", null ],
      [ "Shader", "classshkyera_1_1_shader.html", "classshkyera_1_1_shader" ],
      [ "ShaderProgram", "classshkyera_1_1_shader_program.html", "classshkyera_1_1_shader_program" ],
      [ "SingletonComponent", "structshkyera_1_1_singleton_component.html", null ],
      [ "SkyboxComponent", "structshkyera_1_1_skybox_component.html", "structshkyera_1_1_skybox_component" ],
      [ "Sound", "structshkyera_1_1_sound.html", "structshkyera_1_1_sound" ],
      [ "SparseSet", "classshkyera_1_1_sparse_set.html", "classshkyera_1_1_sparse_set" ],
      [ "SparseSetBase", "classshkyera_1_1_sparse_set_base.html", "classshkyera_1_1_sparse_set_base" ],
      [ "SpotLightComponent", "structshkyera_1_1_spot_light_component.html", "structshkyera_1_1_spot_light_component" ],
      [ "SpotLightComponentUI", "classshkyera_1_1_spot_light_component_u_i.html", "classshkyera_1_1_spot_light_component_u_i" ],
      [ "Texture", "classshkyera_1_1_texture.html", "classshkyera_1_1_texture" ],
      [ "TextureAssetSelector", "classshkyera_1_1_texture_asset_selector.html", "classshkyera_1_1_texture_asset_selector" ],
      [ "ThreadWorker", "classshkyera_1_1_thread_worker.html", "classshkyera_1_1_thread_worker" ],
      [ "TransformComponent", "classshkyera_1_1_transform_component.html", "classshkyera_1_1_transform_component" ],
      [ "TransformComponentUI", "classshkyera_1_1_transform_component_u_i.html", "classshkyera_1_1_transform_component_u_i" ],
      [ "TypeInfo", "structshkyera_1_1_type_info.html", "structshkyera_1_1_type_info" ],
      [ "UI", "classshkyera_1_1_u_i.html", "classshkyera_1_1_u_i" ],
      [ "UseShader", "classshkyera_1_1_use_shader.html", "classshkyera_1_1_use_shader" ],
      [ "Widget", "classshkyera_1_1_widget.html", "classshkyera_1_1_widget" ],
      [ "Wireframe", "classshkyera_1_1_wireframe.html", "classshkyera_1_1_wireframe" ],
      [ "WireframeComponent", "structshkyera_1_1_wireframe_component.html", "structshkyera_1_1_wireframe_component" ],
      [ "WireframeComponentUI", "classshkyera_1_1_wireframe_component_u_i.html", "classshkyera_1_1_wireframe_component_u_i" ],
      [ "WriteAccess", "structshkyera_1_1_write_access.html", "structshkyera_1_1_write_access" ]
    ] ],
    [ "std", "namespacestd.html", [
      [ "std", null, [
        [ "hash< glm::vec3 >", "structstd_1_1std_1_1hash_3_01glm_1_1vec3_01_4.html", "structstd_1_1std_1_1hash_3_01glm_1_1vec3_01_4" ]
      ] ]
    ] ]
];