name: Linux

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        env:
          CXX: g++
        run: |
          git submodule update --init --recursive
          chmod +x build.sh
          ./build.sh
